[package]
name = "libox"
version = "0.1.0"
edition = "2024"

[lib]
name = "libox"
crate-type = ["staticlib"]

[dependencies]
os_socketaddr = "0.2"
libc = "0.2"
winapi = "0.3"
modbus-core = "0.1.1"

[build-dependencies]
bindgen = "0.72"
